### ISSUE TITLE
Cannot turn television on in a flow.

### ISSUE THREAD

**Issue by h3n3b0sch** [jordenc/com.sony.bravia.androidtv#1]
When i make a flow with either a voice-command or a button-command to turn the television on it does not react.
However, if i go to devices in a browser or in my android-app i can turn it on with a click on the logo.

What is the solution to make it work in a flow?

Edit: I'm using homey version 1.0.1 experimental version and the Sony Bravia kd-43x8305c television.

**Comment by jordenc** [comment]
Do you have "Use WOL for Power ON" turned on? You can test that by clicking the wrench on your device under "Devices". Please also let me know if the mac-address is "00:00:00:00:00:00" or something else and if it is empty.

**Comment by h3n3b0sch** [comment]
Yes, everything is set correctly i think because it works when i click the logo in "Devices". It turns the tv on and off.
It just does not work in a flow.

**Comment by jordenc** [comment]
In the "mobile card" where you can click the logo it just executes the command to WakeUp.

In the flow, it checks if the mac address is not "00:00:00:00:00:00" and not empty, and if "Use WOL for Power ON" is checked. If so, it tries to turn it on by WOL (Wake On Lan), otherwise it executes the command to WakeUp.
So therefor, I want to know if Mac address is filled in and the WOL checkbox is checked or not. You might want to try unchecking to see if it works from a flow then.

**Comment by h3n3b0sch** [comment]
Okay, unchecking the box did the trick. Now it turns the tv on. Stupid that i didn't think of trying this myself...

But is this something to change in the code to verify if the box is checked or not so it works the way is should?

**Comment by jordenc** [comment]
Yeah I might build in something so it doesn't check the box automaticly.

Good to hear that it works now!
